apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
          app: db
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db-container
        image: daniellitvak97/db
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: Password123
        ports:
        - containerPort: 3306
