version: '3'

services:

        db:
                build:
                        context: .
                        dockerfile: Dockerfile_db
                image: daniellitvak97/db
                environment:
                        MYSQL_ROOT_PASSWORD: Password123
                ports:
                        - 3309:3306

        app:
                build:
                        context: .
                        dockerfile: Dockerfile_app
                image: daniellitvak97/app
                ports:
                        - 8777:8777
                depends_on:
                        - db

