FROM python:3

RUN pip install flask
RUN pip install PyMySQL

#Can also do this:
#COPY requirements.txt /
#RUN pip install -r ./Python/requirements.txt

COPY ./Python/MainScores.py /

CMD ["python", "MainScores.py"]
