pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                bat "git clone https://github.com/DanielLitvak97/WorldOfGames.git"
            }
        }
        stage('Helm-Install') {
            steps {
	        bat "helm install app-and-db WorldOfGames/Kubernetes/Helm/app-and-db"
            }  
        }
        stage('Test') {
            steps {
	        bat """cd WorldOfGames/Kubernetes/Python/tests
                       python -c "import e2e; e2e.main_function()"""
            }
        }
        stage('Finalize') {
            steps {
	        bat "helm delete app-and-db"
            } 
        }   
    }   
}


