version: '3'

services:
        app:
                build: .
                image: daniellitvak97/app
                ports:
                        - 8777:8777
                volumes:
                        - C:\da\WorldOfGames\Scores.txt:/Scores.txt
  
