pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                bat "git clone https://github.com/DanielLitvak97/WorldOfGames.git"
            }
        }
        stage('Build') {
            steps {
	        bat """cd WorldOfGames/Docker
                       docker-compose build"""
            }  
        }
        stage('Run') {
            steps {
                bat """cd WorldOfGames/Docker
		       docker-compose up -d"""
            }
        }
        stage('Test') {
            steps {
	        bat """cd WorldOfGames/Docker/Python/tests
                       python -c "import e2e; e2e.main_function()"""
            }
        }
        stage('Finalize') {
            steps {
	        bat """cd WorldOfGames/Docker
                       docker-compose down
                       docker-compose push"""
            } 
        }   
    }   
}


