FROM mysql
COPY create_db_and_table.sql /docker-entrypoint-initdb.d
#RUN apt update
#RUN apt install -y python3
#RUN apt install -y python-pip
#RUN pip install PyMySQL

#COPY MySQL_Settings_and_Connection.py /

#CMD ["python", "MySQL_Settings_and_Connection.py"]
